name: Java CI with Maven CA5
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: 'maven'

    - name: Print Java and Maven versions
      run: |
        java -version
        mvn -version

    - name: List Files
      run: ls -la ./Fesadyab

    - name: Build and Test with Maven
      run: mvn clean test -B -e -X -f ./Fesadyab/pom.xml
