name: Java CI with Maven CA5

on:
  push:
    paths: [ "Fesadyab/**" ]
  pull_request:
    paths: [ "Fesadyab/**" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: Fesadyab
      run: mvn clean compile
    - name: Test with Maven
      working-directory: Fesadyab
      run: mvn test
